Document: php-tesseract
Title: Debian php-tesseract Manual
Author: <insert document author here>
Abstract: This manual describes what php-tesseract is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/php-tesseract/php-tesseract.sgml.gz

Format: postscript
Files: /usr/share/doc/php-tesseract/php-tesseract.ps.gz

Format: text
Files: /usr/share/doc/php-tesseract/php-tesseract.text.gz

Format: HTML
Index: /usr/share/doc/php-tesseract/html/index.html
Files: /usr/share/doc/php-tesseract/html/*.html
