/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef PHP_TESSERACT_H
#define PHP_TESSERACT_H

extern zend_module_entry tesseract_module_entry;
#define phpext_tesseract_ptr &tesseract_module_entry

#ifdef PHP_WIN32
# define PHP_TESSERACT_API __declspec(dllexport)
#else
# define PHP_TESSERACT_API
#endif

#ifdef ZTS
#include "TSRM.h"
#endif

PHP_MINIT_FUNCTION(tesseract);
PHP_MSHUTDOWN_FUNCTION(tesseract);
PHP_RINIT_FUNCTION(tesseract);
PHP_RSHUTDOWN_FUNCTION(tesseract);
PHP_MINFO_FUNCTION(tesseract);

ZEND_NAMED_FUNCTION(_wrap_kPointsPerInch_get);
ZEND_NAMED_FUNCTION(_wrap_PTIsLineType);
ZEND_NAMED_FUNCTION(_wrap_PTIsImageType);
ZEND_NAMED_FUNCTION(_wrap_PTIsTextType);
ZEND_NAMED_FUNCTION(_wrap_kPolyBlockNames_get);
ZEND_NAMED_FUNCTION(_wrap_new_TessBaseAPI);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_Version);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_SetInputName);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_SetOutputName);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_SetVariable);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_SetDebugVariable);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_GetIntVariable);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_GetBoolVariable);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_GetDoubleVariable);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_GetStringVariable);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_PrintVariables);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_GetVariableAsString);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_Init);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_GetInitLanguagesAsString);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_GetLoadedLanguagesAsVector);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_InitLangMod);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_InitForAnalysePage);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_ReadConfigFile);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_ReadDebugConfigFile);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_SetPageSegMode);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_GetPageSegMode);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_TesseractRect);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_ClearAdaptiveClassifier);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_SetImage);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_SetSourceResolution);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_SetRectangle);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_GetThresholdedImage);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_GetRegions);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_GetTextlines);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_GetStrips);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_GetWords);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_GetConnectedComponents);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_GetComponentImages);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_GetThresholdedImageScaleFactor);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_DumpPGM);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_AnalyseLayout);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_Recognize);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_RecognizeForChopTest);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_ProcessPages);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_ProcessPage);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_GetIterator);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_GetMutableIterator);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_GetUTF8Text);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_GetHOCRText);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_GetBoxText);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_GetUNLVText);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_MeanTextConf);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_AllWordConfidences);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_AdaptToWordStr);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_Clear);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_End);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_IsValidWord);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_GetTextDirection);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_SetFillLatticeFunc);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_DetectOS);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_GetFeaturesForBlob);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_FindRowForBox);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_RunAdaptiveClassifier);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_GetUnichar);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_GetDawg);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_NumDawgs);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_MakeTessOCRRow);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_MakeTBLOB);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_NormalizeTBLOB);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_tesseract);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_oem);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_InitTruthCallback);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_GetCubeRecoContext);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_set_min_orientation_margin);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_GetBlockTextOrientations);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_FindLinesCreateBlockList);
ZEND_NAMED_FUNCTION(_wrap_TessBaseAPI_DeleteBlockList);
ZEND_NAMED_FUNCTION(_wrap_isLibTiff);
ZEND_NAMED_FUNCTION(_wrap_isLibLept);
ZEND_NAMED_FUNCTION(_wrap_ProcessPagesWrapper);
ZEND_NAMED_FUNCTION(_wrap_ProcessPagesPix);
ZEND_NAMED_FUNCTION(_wrap_ProcessPagesFileStream);
ZEND_NAMED_FUNCTION(_wrap_ProcessPagesBuffer);
ZEND_NAMED_FUNCTION(_wrap_ProcessPagesRaw);
#endif /* PHP_TESSERACT_H */
